### PR TITLE
fix highlighting for seat, mouse_warping, focus_wrapping

### PR DESCRIPTION
**Pull request by sebcode**

### CODE REVIEW

**Comment by jamespeapen** [comment]
Thanks! Would you mind adding a test for the `seat` keyword?

**Comment by sebcode** [comment]
Good point, `seat` wasn't working at all :) Should be fixed.

**Comment by jamespeapen** [comment]
I've split the commits into more atomic ones since I'll eventually be adding the relevant ones to upstream vim.
Thanks for your work!

**Comment by sebcode** [comment]
Thanks a lot. I'll try to produce more granular commits next time if that's preferred!

**Pull request merged**
